### ISSUE TITLE
One Operator per Database

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#125]
To allow for database-specific Storage an Schedule/Retention options, we switch to a dedicated operator per database.

In theory, we only need to change the namespace of a newly created databae from `Postgres.Spec.ProjectID` to the generated database name in [`Postgres.ToPeripheralResourceNamespace()`](https://github.com/fi-ts/postgreslet/blob/main/api/v1/postgres_types.go#L360). This could, in theory, even be configurable.

Currently, the operator itself uses about ~35MB of ressources, the (currently not used) prometheus federation another 60MB. This is considered to be acceptable overhead.

The backup-config still remains as is, but now _has_ to be provided when creating a new database as it can no longer be derived from the project.

**Comment by majst01** [comment]
To make this happen we need to have a Postgres.Spec.BackupID field which references to the secret which stores the backup secrets
