### ISSUE TITLE
make storage class configurable

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#170]
Add config option to postgreslet
Use it when creating the individual postgres cluster

https://postgres-operator.readthedocs.io/en/latest/reference/cluster_manifest/#volume-properties

see https://github.com/metal-stack/csi-driver-lvm#installation , use `csi-lvm-sc-mirror` as default.

**Comment by majst01** [comment]
Chart to use is here: 
https://github.com/metal-stack/helm-charts/tree/master/charts/csi-driver-lvm

**Comment by eberlep** [comment]
Already implemented in #172
