### ISSUE TITLE
Postgres-Operator v1.6.2

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#197]
We should switch from `latest` to `v1.6.2`. According to the changelog, this version contains the fix for the `securityContext` bug that causes the databases to restart every cycle (https://github.com/zalando/postgres-operator/pull/1380).

**Comment by majst01** [comment]
It also adds the ability to specify major PG Version and updates in place as i understood

**Comment by eberlep** [comment]
Maybe already switch to our patched operator image + patched spilo image?

**Comment by eberlep** [comment]
Duplicate of #53
