### ISSUE TITLE
Switch  Check in `IsOperatorDeletable` from Pod to StatefulSet

### ISSUE THREAD

**Issue by eberlep** [fi-ts/postgreslet#83]
## Observed Behaviour
1. We created a `postgres` resource in the control plane cluster (via `kubectl apply -f config/sample/...yaml`)
2. The Postgreslet created a corresponding `postgresql` resource in the service cluster
3. The Postgreslet created an operator in the namespace in the service cluster
4. The operator created the statefulset, secret etc. in the namespace in the service cluster
5. However, due to issues with the PodSecurityPolicy, **no PostgreSQL pod would actually start**
6. To clean up this mess, we removed the `postgres` resource int he control plane cluster (via `kubectl delete -f config/sample/...yaml`)
7. The Postgreslet removed the corresponding `postgresql` resource in the service cluster
8. The Postgreslet deleted the operator in the namespace in the service cluster, all looked clean
9. The next day, we discovered that the statefulsets and secrets were still present

## Analysis
My assumption is that the Operator was removed to early. Since the pods were never actually created, `IsOperatorDeletable` was `true` immediately, even though the operator had not yet cleaned up the sts und secrets.

## Proposal
Hence i propose to at least switch the check in `IsOperatorDeletable` from pods to sts, or even better, check for ALL the resources the opeator manages:
1. Check for Pods
2. If present, also check for sts
3. If present, also check for secrets
4. If present, also check for other, yet to be determined resources the operator manages

**Comment by LimKianAn** [comment]
The current implementation is indeed not satisfying. The best solution would be watching `Postgresql` and checking if there's no more instance, but we are not sure if the mechanism of *finalizer* is implemented. Therefore, we will implement watching `StatefulSet` for the moment.

**Comment by eberlep** [comment]
Just a thought: If this is about cleaning up, we could simply remove the whole namespace once we're done. That's how I cleaned up manually...

**Comment by LimKianAn** [comment]
You mean in this [function](https://github.com/fi-ts/postgreslet/blob/27069958dcd51fb66b7c832a9a43c2c1a0ad29d9/controllers/postgres_controller.go#L228)? Deleting a namespace is clearly a better solution since we don't exactly know what resources are created alongside `Postgresql`. I think the similar concept applies to operator deletion as well.
